files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  class-name-format:
  - 1
  - convention: hyphenatedbem
  id-name-format:
  - 1
  - convention: hyphenatedbem
  placeholder-name-format:
  - 1
  - convention: hyphenatedbem
  property-sort-order:
  - 1
  - order: recess
